name: Android CI

# Disparar o workflow em push ou pull request nas branches especificadas
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar o repositório
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Configurar JDK para Android
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    # 3. Configurar Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    # 4. Instalar dependências do Gradle
    - name: Install dependencies
      run: ./gradlew dependencies

    # 5. Verificar lints do projeto
    - name: Run Android Lint
      run: ./gradlew lint
      continue-on-error: false # Falhar se houver erros de lint

    # 6. Rodar os testes
    - name: Run Unit Tests
      run: ./gradlew test
      continue-on-error: false # Falhar se houver falhas nos testes

    # 7. Compilar o APK
    - name: Build APK
      run: ./gradlew assembleDebug
      continue-on-error: false # Falhar se a build falhar

    # 8. Publicar o APK como um artefato do GitHub
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
